"""Generate downloadable Jupyter notebooks from code snippets."""
import json
import io

def make_notebook(title: str, sections: list) -> bytes:
    """
    sections = [{"heading": str, "markdown": str, "code": str}, ...]
    Returns notebook as bytes for st.download_button.
    """
    cells = []

    # Title cell
    cells.append({
        "cell_type": "markdown",
        "metadata": {},
        "source": [f"# {title}\n", "_Generated by DS Workshop 2026_\n"]
    })

    for section in sections:
        if section.get("heading"):
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [f"## {section['heading']}\n"]
            })
        if section.get("markdown"):
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [section["markdown"]]
            })
        if section.get("code"):
            code = section["code"].strip()
            cells.append({
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [code]
            })

    nb = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0"
            }
        },
        "cells": cells
    }
    return json.dumps(nb, indent=2).encode("utf-8")


# ── Pre-built notebooks per topic ─────────────────────────────────────────────

TOPIC_NOTEBOOKS = {
    "Understanding Data": [
        {"heading": "Setup", "code": "import pandas as pd\nimport numpy as np\nimport plotly.express as px"},
        {"heading": "Create a Dataset", "code": """np.random.seed(42)
n = 1000
engine_data = pd.DataFrame({
    'timestamp':    pd.date_range('2026-06-21', periods=n, freq='1s'),
    'engine_id':    np.random.choice(['ENG-L-001', 'ENG-R-001'], n),
    'egt_celsius':  np.random.normal(640, 15, n),
    'n1_fan_speed': np.random.normal(94, 2, n),
    'vibration':    np.random.exponential(0.4, n),
    'alert_active': np.random.choice([True, False], n, p=[0.05, 0.95]),
    'severity':     np.random.choice(['Normal','Caution','Warning'], n, p=[0.90, 0.08, 0.02])
})
print(engine_data.shape)
engine_data.head()"""},
        {"heading": "Inspect Data Types", "code": "print(engine_data.dtypes)\nprint(engine_data.describe())"},
        {"heading": "Check Data Quality", "code": """print('Missing values:')
print(engine_data.isnull().sum())
print(f'\\nDuplicate rows: {engine_data.duplicated().sum()}')
print(f'\\nUnique engines: {engine_data[\"engine_id\"].nunique()}')"""},
        {"heading": "Distribution Plot", "code": """fig = px.histogram(engine_data, x='egt_celsius', nbins=40,
                   color='engine_id', barmode='overlay',
                   title='EGT Distribution by Engine')
fig.show()"""},
    ],
    "Data Cleaning": [
        {"heading": "Setup", "code": "import pandas as pd\nimport numpy as np\nfrom sklearn.impute import SimpleImputer, KNNImputer"},
        {"heading": "Inject Dirty Data", "code": """np.random.seed(7)
df = pd.DataFrame({
    'temperature': np.random.normal(22, 5, 200),
    'vibration':   np.random.exponential(0.4, 200),
    'material':    np.random.choice(['steel', 'Steel', 'STEEL', 'aluminum'], 200),
    'pressure':    np.random.normal(100, 10, 200),
})
# Inject issues
df.loc[np.random.choice(200, 20), 'temperature'] = np.nan
df.loc[np.random.choice(200, 5), 'vibration'] = 999.9   # sentinel
df = pd.concat([df, df.iloc[:5]])                        # duplicates
print(df.isnull().sum())"""},
        {"heading": "Handle Missing Values", "code": """df['temperature'].fillna(df['temperature'].median(), inplace=True)
print('Missing after fill:', df['temperature'].isnull().sum())"""},
        {"heading": "Handle Outliers (IQR)", "code": """Q1 = df['vibration'].quantile(0.25)
Q3 = df['vibration'].quantile(0.75)
IQR = Q3 - Q1
df['vibration'] = df['vibration'].clip(Q1 - 1.5*IQR, Q3 + 1.5*IQR)
print(df['vibration'].describe())"""},
        {"heading": "Fix String Inconsistencies", "code": """df['material'] = df['material'].str.strip().str.title()
df['material'] = df['material'].replace({'Steel': 'Steel', 'Aluminum': 'Aluminum'})
print(df['material'].value_counts())"""},
        {"heading": "Remove Duplicates", "code": """print('Before:', len(df))
df.drop_duplicates(inplace=True)
print('After:', len(df))"""},
    ],
    "Data Processing": [
        {"heading": "Setup", "code": """import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer"""},
        {"heading": "Sample Dataset", "code": """df = pd.DataFrame({
    'material':     np.random.choice(['Steel', 'Aluminum', 'Copper'], 300),
    'thickness':    np.random.normal(10, 0.3, 300),
    'hardness':     np.random.normal(58, 3, 300),
    'temperature':  np.random.normal(22, 5, 300),
    'passed_qc':    np.random.choice([True, False], 300, p=[0.92, 0.08]),
})
df.head()"""},
        {"heading": "Encoding Categoricals", "code": """# One-hot encoding
df_encoded = pd.get_dummies(df, columns=['material'], drop_first=False)
print(df_encoded.columns.tolist())"""},
        {"heading": "Scaling Numericals", "code": """num_cols = ['thickness', 'hardness', 'temperature']
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])
print(df[num_cols].describe().round(3))"""},
        {"heading": "Full sklearn Pipeline", "code": """numeric_features = ['thickness', 'hardness', 'temperature']
categorical_features = ['material']

preprocessor = ColumnTransformer([
    ('num', Pipeline([
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler',  StandardScaler()),
    ]), numeric_features),
    ('cat', Pipeline([
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False)),
    ]), categorical_features),
])

X = df[numeric_features + categorical_features]
X_transformed = preprocessor.fit_transform(X)
print('Shape after preprocessing:', X_transformed.shape)"""},
    ],
    "EDA": [
        {"heading": "Setup", "code": "import pandas as pd\nimport numpy as np\nimport plotly.express as px\nimport plotly.graph_objects as go"},
        {"heading": "Load Data", "code": """np.random.seed(42)
df = pd.DataFrame({
    'tenure_months':   np.random.randint(1, 72, 400),
    'monthly_charges': np.random.normal(65, 20, 400),
    'num_complaints':  np.random.poisson(0.5, 400),
    'data_usage_gb':   np.random.exponential(15, 400),
    'contract_type':   np.random.choice(['Month-to-month','One year','Two year'], 400),
    'churned':         np.random.choice([True, False], 400, p=[0.27, 0.73]),
})
print(df.shape)
df.describe()"""},
        {"heading": "Missing Values", "code": """print(df.isnull().sum())
print(f'\\nMissing %:\\n{df.isnull().mean() * 100}')"""},
        {"heading": "Distributions", "code": """fig = px.histogram(df, x='monthly_charges', nbins=40,
                   title='Monthly Charges Distribution')
fig.show()
print(f'Skewness: {df[\"monthly_charges\"].skew():.3f}')"""},
        {"heading": "Churn Rate by Contract", "code": """churn_by_contract = df.groupby('contract_type')['churned'].mean().reset_index()
churn_by_contract['churn_pct'] = churn_by_contract['churned'] * 100
fig = px.bar(churn_by_contract, x='contract_type', y='churn_pct',
             title='Churn Rate by Contract Type (%)')
fig.show()"""},
        {"heading": "Correlation Matrix", "code": """import plotly.graph_objects as go
num_df = df.select_dtypes(include=np.number)
num_df['churned_int'] = df['churned'].astype(int)
corr = num_df.corr()
fig = go.Figure(go.Heatmap(z=corr.values, x=corr.columns, y=corr.index,
                            colorscale='RdBu', zmid=0,
                            text=corr.round(2).values, texttemplate='%{text}'))
fig.update_layout(title='Correlation Matrix')
fig.show()"""},
    ],
    "ML Fundamentals": [
        {"heading": "Setup", "code": """import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer"""},
        {"heading": "Generate Dataset", "code": """np.random.seed(42)
n = 400
df = pd.DataFrame({
    'tenure_months':   np.random.randint(1, 72, n),
    'monthly_charges': np.random.normal(65, 20, n),
    'num_complaints':  np.random.poisson(0.5, n),
    'contract_type':   np.random.choice(['Month-to-month','One year','Two year'], n),
    'churned':         np.random.choice([0, 1], n, p=[0.73, 0.27]),
})
print(df['churned'].value_counts())"""},
        {"heading": "Build Pipeline", "code": """numeric_features = ['tenure_months', 'monthly_charges', 'num_complaints']
categorical_features = ['contract_type']

preprocessor = ColumnTransformer([
    ('num', Pipeline([('imp', SimpleImputer()), ('sc', StandardScaler())]), numeric_features),
    ('cat', Pipeline([('imp', SimpleImputer(strategy='most_frequent')),
                      ('enc', OneHotEncoder(handle_unknown='ignore', sparse_output=False))]),
     categorical_features),
])

model = Pipeline([
    ('pre', preprocessor),
    ('clf', RandomForestClassifier(n_estimators=100, random_state=42)),
])"""},
        {"heading": "Train and Evaluate", "code": """X = df.drop('churned', axis=1)
y = df['churned']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                      stratify=y, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print(f'ROC AUC: {roc_auc_score(y_test, y_prob):.3f}')
print(classification_report(y_test, y_pred))"""},
        {"heading": "Feature Importance", "code": """import plotly.express as px
fi = pd.Series(
    model.named_steps['clf'].feature_importances_,
    index=numeric_features + list(
        model.named_steps['pre'].named_transformers_['cat']
        .named_steps['enc'].get_feature_names_out(categorical_features)
    )
).sort_values(ascending=False)

fig = px.bar(fi.reset_index(), x='index', y=0,
             title='Feature Importance')
fig.show()"""},
    ],
    "Visualization": [
        {"heading": "Setup", "code": "import pandas as pd\nimport numpy as np\nimport plotly.express as px\nimport plotly.graph_objects as go\nfrom plotly.subplots import make_subplots"},
        {"heading": "Sample Data", "code": """np.random.seed(42)
df = pd.DataFrame({
    'material':    np.random.choice(['Steel', 'Aluminum', 'Copper'], 300),
    'thickness':   np.random.normal(10, 0.3, 300),
    'hardness':    np.random.normal(58, 3, 300),
    'temperature': np.random.normal(22, 5, 300),
    'passed_qc':   np.random.choice([True, False], 300, p=[0.92, 0.08]),
    'timestamp':   pd.date_range('2026-06-01', periods=300, freq='1h'),
})"""},
        {"heading": "Histogram", "code": """fig = px.histogram(df, x='thickness', color='material',
                   nbins=40, barmode='overlay', opacity=0.8,
                   title='Thickness Distribution by Material')
fig.update_layout(template='plotly_dark')
fig.show()"""},
        {"heading": "Box Plot", "code": """fig = px.box(df, x='material', y='hardness', color='material',
             points='outliers', title='Hardness by Material')
fig.update_layout(template='plotly_dark')
fig.show()"""},
        {"heading": "Scatter Plot", "code": """fig = px.scatter(df, x='thickness', y='hardness',
                 color='material', opacity=0.7,
                 title='Hardness vs Thickness')
fig.update_layout(template='plotly_dark')
fig.show()"""},
        {"heading": "Correlation Heatmap", "code": """corr = df[['thickness', 'hardness', 'temperature']].corr()
fig = go.Figure(go.Heatmap(z=corr.values, x=corr.columns, y=corr.index,
                            colorscale='RdBu', zmid=0,
                            text=corr.round(2).values, texttemplate='%{text}'))
fig.update_layout(title='Correlation Matrix', template='plotly_dark')
fig.show()"""},
        {"heading": "Time Series", "code": """fig = px.line(df, x='timestamp', y='temperature',
              title='Temperature Over Time')
fig.update_layout(template='plotly_dark')
fig.show()"""},
        {"heading": "Dashboard (subplots)", "code": """fig = make_subplots(rows=2, cols=2,
    subplot_titles=['Thickness Dist', 'Thickness by Material',
                    'Hardness vs Thickness', 'QC Pass Rate'])

for mat in df['material'].unique():
    d = df[df['material']==mat]['thickness']
    fig.add_trace(go.Histogram(x=d, name=mat, opacity=0.7), row=1, col=1)

fig.add_trace(go.Box(x=df['material'], y=df['thickness'], name='Thickness'), row=1, col=2)

fig.add_trace(go.Scatter(x=df['thickness'], y=df['hardness'],
    mode='markers', marker=dict(opacity=0.5), name='Points'), row=2, col=1)

pass_rate = df.groupby('material')['passed_qc'].mean().reset_index()
fig.add_trace(go.Bar(x=pass_rate['material'], y=pass_rate['passed_qc'],
    marker_color='#10b981', name='Pass Rate'), row=2, col=2)

fig.update_layout(template='plotly_dark', height=700, title='Manufacturing Dashboard')
fig.show()"""},
    ],
}
